apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: kube-logging
  labels:
    app: elasticsearch
spec:
  ports:
  - protocol: TCP
    port: 9200
    targetPort: 9200
    name: rest
  - protocol: TCP
    port: 9300
    targetPort: 9300
    name: inter-node
  selector:
    app: elasticsearch
